[[main]]
  name = "Startseite"
  weight = 5
  url = "/docs/startseite/login"

[[docs]]
  name = "Startseite"
  weight = 10
  identifier = "startseite"
  url = "/docs/startseite/"



[[footer]]
  name = "Tel: 	0221 2222 995"
  url = "https://www.netcologne.de/geschaeftskunden/kontakt/kontaktformular/"
  weight = 10
