[[main]]
  name = "Dokumentation"
  weight = 5
  url = "/docs/startseite/login"

[[docs]]
  name = "Startseite"
  weight = 10
  identifier = "startseite"
  url = "/docs/startseite/"

[[docs]]
  name = "Belegschaft"
  weight = 20
  identifier = "belegschaft"
  url = "/docs/belegschaft/"

[[docs]]
  name = "Daten"
  weight = 30
  identifier = "daten"
  url = "/docs/daten/"

[[docs]]
  name = "Anrufannahme"
  weight = 40
  identifier = "anrufannahme"
  url = "/docs/anrufannahme/"

[[docs]]
  name = "System"
  weight = 50
  identifier = "system"
  url = "/docs/system/"

[[footer]]
  name = "Tel: 	0221 2222 995"
  url = "https://www.netcologne.de/geschaeftskunden/kontakt/kontaktformular/"
  weight = 10
